### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by mnoto-one** [dev-yakuza/study-flutter#2]
#Error:
 No pubspec.yaml file found.
This command should be run from the root of your Flutter project.

**Comment by dev-yakuza** [comment]
@mnoto-one What is the question?

If you want to check the code, go to the specific folder first.

- https://github.com/dev-yakuza/study-flutter/tree/main/examples/dice

And then, execute the `flutter get` or just open the IDE.(it may execute the `flutter get` automatically.)

And run the code with the simulator.

If your question is not it, give me more details.

**Comment by mnoto-one** [comment]
Thanks Sloved
